/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;

<<<<<<< HEAD
//<<<<<<< HEAD

import DAO.usersDAO;
import Utils.Auth;
import Utils.MsgBox;
import entity.users;
//=======
=======
>>>>>>> 52f02550b31efef30be7f4fecc60ef69537ff999
import DAO.usersDAO;
import Utils.Auth;
import Utils.MsgBox;
import Utils.jdbchelper;
import entity.users;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
<<<<<<< HEAD
//>>>>>>> 52f02550b31efef30be7f4fecc60ef69537ff999
=======
>>>>>>> 52f02550b31efef30be7f4fecc60ef69537ff999

/**
 *
 * @author akbro
 */
public class FormDangNhap extends javax.swing.JFrame {

<<<<<<< HEAD
//<<<<<<< HEAD

//=======
//>>>>>>> 52f02550b31efef30be7f4fecc60ef69537ff999
=======
>>>>>>> 52f02550b31efef30be7f4fecc60ef69537ff999
    public FormDangNhap() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txttaikhoan = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dosis ExtraBold", 1, 24)); // NOI18N
        jLabel1.setText("Đăng nhập");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 28, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/user.png"))); // NOI18N
        jLabel2.setText("Tài khoản:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 71, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/key.png"))); // NOI18N
        jLabel3.setText("Mật khẩu:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 121, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Đổi mật khẩu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("Đăng nhập");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 179, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Chicken-LOGO1 2.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 53, 174, 184));
        jPanel2.add(txttaikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 220, -1));
        jPanel2.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txttaikhoan;
    // End of variables declaration//GEN-END:variables
<<<<<<< HEAD
//<<<<<<< HEAD
    
    usersDAO dao=new usersDAO();
    private void Login() {
        String manv=txttaikhoan.getText();
        String matkhau=new String(txtpass.getPassword());
        users us=dao.selectByid(manv);
        if(us==null){
            MsgBox.alert(this,"Sai tên đăng nhập!");
        }else if(!matkhau.equals(us.getMatkhau())){
            MsgBox.alert(this,"Sai mật khẩu!");
        }else{
            Auth.user=us;
            this.dispose();
        }
//=======

    usersDAO dao = new usersDAO();

//    private void Login() {
//        String manv = txttaikhoan.getText();
//        String matkhau = new String(txtpass.getPassword());
//        users us = dao.selectByid(manv);
//        if (us == null) {
//            MsgBox.alert(this, "Sai tên đăng nhập!");
//        } else if (!matkhau.equals(us.getMatkhau())) {
//            MsgBox.alert(this, "Sai mật khẩu!");
//        } else {
//            Auth.user = us;
//            this.dispose();
//            FormQuanLi frmql = new FormQuanLi();
//            frmql.setVisible(true);
//        }

//>>>>>>> 52f02550b31efef30be7f4fecc60ef69537ff999
=======

    usersDAO dao = new usersDAO();

    private void Login() {
        String manv = txttaikhoan.getText();
        String matkhau = new String(txtpass.getPassword());
        users us = dao.selectByid(manv);
        if (us == null) {
            MsgBox.alert(this, "Sai tên đăng nhập!");
        } else if (!matkhau.equals(us.getMatkhau())) {
            MsgBox.alert(this, "Sai mật khẩu!");
        } else {
            Auth.user = us;
            this.dispose();
            FormQuanLi frmql = new FormQuanLi();
            frmql.setVisible(true);
        }

>>>>>>> 52f02550b31efef30be7f4fecc60ef69537ff999
    }

    private void init() {
        this.setLocationRelativeTo(null);

    }
}
